### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by sergiocorreia** [pandoc-extras/pandocpm#1]
Not sure what name to pick

- Short names are faster
- Long names are easier to grasp (and possibly to remember)

**Comment by ickc** [comment]
you mean the name of `pandocpm`?

Brain-storming:

- [ ] `pdmgr`: `PanDoc ManaGeR`, from `tlmgr` as TeXLive Manager
- [x] `pacdoc`: wordplay
- [ ] `packdoc`: variant of the previous one
- [ ] `pif`: `Pif Installs Filters`, from `pip` as `PIP Installs Packages`
- [ ] `pandocbrew`: from homebrew
- [ ] `panbrew`: variant of the previous one
- [x] `panfill`: wordplay on pandoc and polyfill

checked are my favorites. `pacdoc` might works better as a package manager while `panfill` might fit better as an organization name.

**Comment by sergiocorreia** [comment]
I'm fine with both, and also with `pandocpm`. Maybe we can also ask the folks at the google group...

**Comment by ickc** [comment]
After letting it sink for a few days, I think I prefer `pacdoc` the best. It is catchy and easy to type. For things like `tlmgr`, every time I type that I was saying "TeX Live Manager" in my mind, which makes it slower to type. What do you think?

**Comment by ickc** [comment]
Ah, I see that @sergiocorreia already setup pandocpm, so renaming can be a problem.

And by the way, can @sergiocorreia add the pypi password in Travis CI in the same way did in panflute? Then I can setup Travis to push to there.

**Comment by sergiocorreia** [comment]
Done. About the renaming, it can be done (just rename repo and delete pypi package), but my only concern is that people would type "packdoc" instead of "pacdoc" (unless maybe if you have arch linux and use pacman)

**Comment by ickc** [comment]
About the travis deploy, since it is built from my travis, and my travis don't have your password, it doesn't work.

A proper way to do it would be add me as maintainer in PyPI's pandocpm, then I can use my own PyPI password in my Travis.

But we should do that *after* we finalized the name though.

Another name popped up in my mind a few hours ago is something like `papm` stands for "papm ain't package manager". Kind of old tricks, but emphasize that it ain't managing the versions for example. One thing I worry about the name `pandocpm` is it might set the expectation higher than what we build it for.

Edit: typo

**Comment by sergiocorreia** [comment]
> About the travis deploy, since it is built from my travis, and my travis don't have your password, it doesn't work.

BTW, I just added the pypi_password env variable to my TravisCI for the project, so it should work as with e.g. panflute

**Comment by ickc** [comment]
> BTW, I just added the pypi_password env variable to my TravisCI for the project, so it should work as with e.g. panflute

Right, the Travis is actually pandoc-extras, not ickc's, so it should work.

It almost work, but

```
HTTPError: 401 Client Error: You must be identified to edit package information for url: https://pypi.python.org/pypi
```

I don't know what's going on.

**Comment by ickc** [comment]
Ah, I know it now. Fixed Travis config in bb067cb.

**Comment by ickc** [comment]
@sergiocorreia 
About the package name: I guess no one really cares which exact name to use. So I'll let you decide which one you like most and we can stick with it.

**Comment by sergiocorreia** [comment]
I would just leave it as it is. I'm a bit short of time these days (holidays, work, etc) but I'll try to push an update on the most important features after that.

**Comment by ickc** [comment]
Sure. Let's close this issue then.

When I have time, I will try to read through and see what I can do too. The "deadline" I was having is about mid-Jan, before next semester starts, for collaborations between GSIs to edit a workbook. But now that project becomes dormant due to budget issue, so I don't have such deadline anymore.
